name: simspace
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  # Python dependencies
  - python=3.11.9
  - numpy
  - pandas
  - scanpy
  - seaborn
  - matplotlib
  - scipy
  - typing
  - colorcet
  - esda
  - libpysal
  - scikit-learn
  - umap-learn

  # Dependencies for development
  - pytest          # ✅ dev-only
  - coverage        # optional: test coverage
  - pre-commit      # optional: code linting
  - pip
  - pip:
      - -e .        # editable install of simspace